title: Capsule
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/

markdown: kramdown
highligeter: pygments
lsi: false
safe: true

permalink: pretty
relative_permalinks: false

excerpt_separator: "<!-- more -->"

Parallel Universe:
  # Blog Information
  title:        "Parallel Universe blog"
  cover_image:  blog-cover.jpg

  # Company information
  company:      Parallel Universe Software Co.
  url:          http://paralleluniverse.co/
  facebook:     puniverseco
  twitter:      puniverse

# tagged
tag_page_layout: tagged
tag_page_dir: tagged
