markdown: enhanced_kramdown
highlighter: pygments
lsi: false
safe: false
baseurl: /quasar

## Site globals used throughout docs.
project: Quasar
version: 0.6.2
github: puniverse/quasar
google_group: "https://groups.google.com/forum/#!forum/quasar-pulsar-user"
ga_tracking_id: UA-25007319-2
